/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary) / 0.05)',
          100: 'rgb(var(--color-primary) / 0.1)',
          200: 'rgb(var(--color-primary) / 0.2)',
          300: 'rgb(var(--color-primary) / 0.3)',
          400: 'rgb(var(--color-primary) / 0.4)',
          500: 'rgb(var(--color-primary) / 0.6)',
          600: 'rgb(var(--color-primary) / 0.8)',
          700: 'rgb(var(--color-primary) / 0.9)',
          800: 'rgb(var(--color-primary) / 0.95)',
          900: 'rgb(var(--color-primary) / 1)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary) / 0.05)',
          100: 'rgb(var(--color-secondary) / 0.1)',
          200: 'rgb(var(--color-secondary) / 0.2)',
          300: 'rgb(var(--color-secondary) / 0.3)',
          400: 'rgb(var(--color-secondary) / 0.4)',
          500: 'rgb(var(--color-secondary) / 0.6)',
          600: 'rgb(var(--color-secondary) / 0.8)',
          700: 'rgb(var(--color-secondary) / 0.9)',
          800: 'rgb(var(--color-secondary) / 0.95)',
          900: 'rgb(var(--color-secondary) / 1)',
        },
        accent: {
          50: 'rgb(var(--color-accent) / 0.05)',
          100: 'rgb(var(--color-accent) / 0.1)',
          200: 'rgb(var(--color-accent) / 0.2)',
          300: 'rgb(var(--color-accent) / 0.3)',
          400: 'rgb(var(--color-accent) / 0.4)',
          500: 'rgb(var(--color-accent) / 0.6)',
          600: 'rgb(var(--color-accent) / 0.8)',
          700: 'rgb(var(--color-accent) / 0.9)',
          800: 'rgb(var(--color-accent) / 0.95)',
          900: 'rgb(var(--color-accent) / 1)',
        },
        success: {
          50: 'rgb(var(--color-success) / 0.05)',
          100: 'rgb(var(--color-success) / 0.1)',
          200: 'rgb(var(--color-success) / 0.2)',
          300: 'rgb(var(--color-success) / 0.3)',
          400: 'rgb(var(--color-success) / 0.4)',
          500: 'rgb(var(--color-success) / 0.6)',
          600: 'rgb(var(--color-success) / 0.8)',
          700: 'rgb(var(--color-success) / 0.9)',
          800: 'rgb(var(--color-success) / 0.95)',
          900: 'rgb(var(--color-success) / 1)',
        },
        warning: {
          50: 'rgb(var(--color-warning) / 0.05)',
          100: 'rgb(var(--color-warning) / 0.1)',
          200: 'rgb(var(--color-warning) / 0.2)',
          300: 'rgb(var(--color-warning) / 0.3)',
          400: 'rgb(var(--color-warning) / 0.4)',
          500: 'rgb(var(--color-warning) / 0.6)',
          600: 'rgb(var(--color-warning) / 0.8)',
          700: 'rgb(var(--color-warning) / 0.9)',
          800: 'rgb(var(--color-warning) / 0.95)',
          900: 'rgb(var(--color-warning) / 1)',
        },
        error: {
          50: 'rgb(var(--color-error) / 0.05)',
          100: 'rgb(var(--color-error) / 0.1)',
          200: 'rgb(var(--color-error) / 0.2)',
          300: 'rgb(var(--color-error) / 0.3)',
          400: 'rgb(var(--color-error) / 0.4)',
          500: 'rgb(var(--color-error) / 0.6)',
          600: 'rgb(var(--color-error) / 0.8)',
          700: 'rgb(var(--color-error) / 0.9)',
          800: 'rgb(var(--color-error) / 0.95)',
          900: 'rgb(var(--color-error) / 1)',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      spacing: {
        '8xl': '96rem',
        '9xl': '128rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-in': 'slideIn 0.5s ease-out',
        'pulse-slow': 'pulse 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};